# global

#spotify
mobileapptracking.com
sc-analytics.appspot.com
app-analytics.snapchat.com
https://www.surveygizmo.com/
d2bnxibecyz4h5.cloudfront.net/runtimejs/intercept/intercept.js
creative.ak.fbcdn.net
external-lhr0-1.xx.fbcdn.net
external-lhr1-1.xx.fbcdn.net
external-lhr10-1.xx.fbcdn.net
external-lhr2-1.xx.fbcdn.net
external-lhr3-1.xx.fbcdn.net
external-lhr4-1.xx.fbcdn.net
external-lhr5-1.xx.fbcdn.net
external-lhr6-1.xx.fbcdn.net
external-lhr7-1.xx.fbcdn.net
external-lhr8-1.xx.fbcdn.net
external-lhr9-1.xx.fbcdn.net
fbcdn-creative-a.akamaihd.net
scontent-lhr3-1.xx.fbcdn.net
scontent.xx.fbcdn.net
scontent.fgdl5-1.fna.fbcdn.net
graph.facebook.com
connect.facebook.com
adclick.g.doublecklick.net
adeventtracker.spotify.com
ads-fa.spotify.com
analytics.spotify.com
audio2.spotify.com
b.scorecardresearch.com
bounceexchange.com
bs.serving-sys.com
content.bitsontherun.com
core.insightexpressai.com
crashdump.spotify.com
d2gi7ultltnc2u.cloudfront.net
d3rt1990lpmkn.cloudfront.net
desktop.spotify.com

#other crap

doubleclick.net
ds.serving-sys.com
googleadservices.com
googleads.g.doubleclick.net
gtssl2-ocsp.geotrust.com
js.moatads.com
log.spotify.com
media-match.com
omaze.com
open.spotify.com
pagead46.l.doubleclick.net
pagead2.googlesyndication.com
partner.googleadservices.com
pubads.g.doubleclick.net
redirector.gvt1.com
s0.2mdn.net
securepubads.g.doubleclick.net
spclient.wg.spotify.com
tpc.googlesyndication.com
v.jwpcdn.com
video-ad-stats.googlesyndication.com
weblb-wg.gslb.spotify.com
www.googleadservices.com
www.googletagservices.com

www.omaze.com
media-match.com
adclick.g.doublecklick.net
www.googleadservices.com
open.spotify.com
pagead2.googlesyndication.com
desktop.spotify.com
googleads.g.doubleclick.net
pubads.g.doubleclick.net
securepubads.g.doubleclick.net
audio2.spotify.com
http://audio2.spotify.com
www.audio2.spotify.com
www.omaze.com
omaze.com
bounceexchange.com
core.insightexpressai.com
content.bitsontherun.com
s0.2mdn.net
v.jwpcdn.com
d2gi7ultltnc2u.cloudfront.net
crashdump.spotify.com
adeventtracker.spotify.com
log.spotify.com
analytics.spotify.com
ads-fa.spotify.com
cs283.wpc.teliasoneracdn.net
audio-ec.spotify.com
cs126.wpc.teliasoneracdn.net
heads-ec.spotify.com
u.scdn.co
cs126.wpc.edgecastcdn.net
pagead46.l.doubleclick.net
pagead.l.doubleclick.net
video-ad-stats.googlesyndication.com
pagead-googlehosted.l.google.com
partnerad.l.doubleclick.net
prod.spotify.map.fastlylb.net
adserver.adtechus.com
na.gmtdmp.com
anycast.pixel.adsafeprotected.com
ads.pubmatic.com
idsync-ext.rlcdn.com
www.googletagservices.com
sto3.spotify.com
spclient.wg.spotify.com
d361oi6ppvq2ym.cloudfront.net
gads.pubmatic.com
ads-west-colo.adsymptotic.com
geo3.ggpht.com
showads33000.pubmatic.com
spclient.wg.spotify.com

e1723.dscd.akamaiedge.net
officecdn.microsoft.com.edgesuite.net
crl.globalsign.net
hangouts.google.com
plus.l.google.com
isatap.lan
pinpoll.com
pinpoll.azureedge.net
s.w.org
s902.vshare.io

##https://freedom-to-tinker.com/2018/04/18/no-boundaries-for-facebook-data-third-party-trackers-abuse-facebook-login/

tribunnews.com
st-a.props.id
kompas.com
st-a.props.id
liputan6.com
st-a.props.id
kapanlagi.com
st-a.props.id
merdeka.com
st-a.props.id
bola.net
st-a.props.id
bintang.com
st-a.props.id
tempo.co
st-a.props.id
dream.co.id
st-a.props.id
vidio.com
st-a.props.id
wykop.pl
api.behavioralengine.com
kompasiana.com
st-a.props.id
trustedreviews.com
tags.tiqcdn.com
oneplus.net
cdn4.forter.com
money.pl
api.behavioralengine.com
bola.com
st-a.props.id
mongodb.com
cdn.augur.io
bigstockphoto.com
cdn.augur.io
bandsintown.com
srv.clickfuse.com
svpressa.ru
p1.ntvk1.ru
photoshelter.com
cdn.augur.io
mindbodygreen.com
cdn.augur.io
nme.com
tags.tiqcdn.com
brilio.net
st-a.props.id
juara.net
st-a.props.id
jomashop.com
cdn4.forter.com
tekstowo.pl
api.behavioralengine.com
smotri.com
p1.ntvk1.ru
tonkosti.ru
p1.ntvk1.ru
bose.com
cdn4.forter.com
otomotifnet.com
st-a.props.id
kiwi.com
cdn4.forter.com
songlyrics.com
srv.clickfuse.com
otomania.com
st-a.props.id
drmartens.com
c.lytics.io
digitalmarketer.com
cdn.augur.io
dziennik.pl
api.behavioralengine.com
dollskill.com
cdn4.forter.com
convertkit.com
cdn.augur.io
macsales.com
cdn4.forter.com
vemale.com
st-a.props.id
joomag.com
cdn.augur.io
gazetaprawna.pl
api.behavioralengine.com
raise.com
cdn4.forter.com
moneymorning.com
c.lytics.io
lyricsmania.com
srv.clickfuse.com
swimoutlet.com
cdn4.forter.com
goodtoknow.co.uk
tags.tiqcdn.com
marieclaire.co.uk
tags.tiqcdn.com
shopspring.com
cdn4.forter.com
parade.com
c.lytics.io
wallpaper.com
tags.tiqcdn.com
sputnikmusic.com
srv.clickfuse.com
letssingit.com
srv.clickfuse.com
cableone.net
cdn.augur.io
relevantmagazine.com
c.lytics.io
coveralia.com
srv.clickfuse.com
booktopia.com.au
cdn4.forter.com
activecampaign.com
cdn.augur.io
cyclingweekly.co.uk
tags.tiqcdn.com
datastax.com
c.lytics.io
forsal.pl
api.behavioralengine.com
intisari-online.com
st-a.props.id
amiclubwear.com
cdn4.forter.com
zenplanner.com
cdn.augur.io
livingspaces.com
cdn4.forter.com
sonichits.com
srv.clickfuse.com
skillcrush.com
cdn.augur.io
precisionnutrition.com
cdn.augur.io
fullcompass.com
cdn4.forter.com
careerfoundry.com
cdn.augur.io
otosia.com
st-a.props.id
convertkit-mail.com
cdn.augur.io
blinq.com
cdn4.forter.com
worldofwatches.com
cdn4.forter.com
actonsoftware.com
c.lytics.io
fotosik.pl
api.behavioralengine.com
dixipay.com
cdn.augur.io
niezlomni.com
api.behavioralengine.com
delivery.com
cdn4.forter.com
opb.org
c.lytics.io
auto.com.pl
api.behavioralengine.com
melodyfacts.com
srv.clickfuse.com
bellacor.com
cdn4.forter.com
azchords.com
srv.clickfuse.com
ybw.com
tags.tiqcdn.com
audiostereo.pl
api.behavioralengine.com
drhtv.com.pl
api.behavioralengine.com
mongodb.org
cdn.augur.io
cnenergy.org
cdn.augur.io
rainbowshops.com
cdn4.forter.com
szkolnictwo.pl
api.behavioralengine.com
lyrics.com
srv.clickfuse.com
quimbee.com
cdn.augur.io
pap.pl
api.behavioralengine.com
parolesmania.com
srv.clickfuse.com
mbsy.co
cdn.augur.io
augur.io
cdn.augur.io
facetemjestem.pl
api.behavioralengine.com
nf.pl
api.behavioralengine.com
bebzol.com
api.behavioralengine.com
indieshuffle.com
srv.clickfuse.com
gyft.com
cdn4.forter.com
cedexis.com
c.lytics.io
kunversion.com
cdn.augur.io
tabloidnova.com
st-a.props.id
fastbill.com
cdn.augur.io
weber.com
cdn4.forter.com
amateurphotographer.co.uk
tags.tiqcdn.com
housetohome.co.uk
tags.tiqcdn.com
ising.pl
api.behavioralengine.com
rap4ever.net
srv.clickfuse.com
hbcubuzz.com
srv.clickfuse.com
yogaoutlet.com
cdn4.forter.com
styl.fm
api.behavioralengine.com
instyle.co.uk
tags.tiqcdn.com
hiphop-n-more.com
srv.clickfuse.com
cardcash.com
cdn4.forter.com
designhill.com
cdn.augur.io
horseandhound.co.uk
tags.tiqcdn.com
pajacyk.pl
api.behavioralengine.com
elyrics.net
srv.clickfuse.com
onemonth.com
cdn.augur.io
digitalstorm.com
cdn.augur.io
citizenwatch.com
cdn4.forter.com
whatdigitalcamera.com
tags.tiqcdn.com
domy.pl
api.behavioralengine.com
oldielyrics.com
srv.clickfuse.com
decanter.com
tags.tiqcdn.com
appeagle.com
cdn.augur.io
getambassador.com
cdn.augur.io
justworks.com
cdn.augur.io
sooperboy.com
st-a.props.id
gruntstyle.com
cdn.augur.io
mbr.co.uk
tags.tiqcdn.com
shopwithscrip.com
cdn.augur.io
soccerpro.com
cdn.augur.io
lyricsfeast.com
srv.clickfuse.com
bench.co
cdn.augur.io
questnutrition.com
cdn4.forter.com
look.co.uk
tags.tiqcdn.com
tstatic.net
st-a.props.id
diymag.com
srv.clickfuse.com
awaytravel.com
cdn4.forter.com
celebsnow.co.uk
tags.tiqcdn.com
windows7forum.pl
api.behavioralengine.com
yourchords.com
srv.clickfuse.com
romwod.com
cdn.augur.io
smiledirectclub.com
cdn.augur.io
codeguard.com
cdn.augur.io
realtyshares.com
cdn.augur.io
heels.com
cdn4.forter.com
autobild.co.id
st-a.props.id
upstart.com
cdn.augur.io
moosend.com
cdn.augur.io
tinymixtapes.com
srv.clickfuse.com
karelinform.ru
p1.ntvk1.ru
slowka.pl
api.behavioralengine.com
rga.com
c.lytics.io
purina.com
c.lytics.io
dentresearch.com
c.lytics.io
auto.pl
api.behavioralengine.com
act-on.com
c.lytics.io
zebra-tv.ru
p1.ntvk1.ru
otonomi.co.id
st-a.props.id
lyrster.com
srv.clickfuse.com
headlineplanet.com
srv.clickfuse.com
iquitsugar.com
cdn.augur.io
motorplus-online.com
st-a.props.id
internationalman.com
c.lytics.io
neverbounce.com
cdn.augur.io
learnersedgeinc.com
cdn.augur.io
freeflysystems.com
cdn.augur.io
hai-online.com
st-a.props.id
4inkjets.com
cdn4.forter.com
gpwinfostrefa.pl
api.behavioralengine.com
perkbox.co.uk
cdn.augur.io
coinmama.com
cdn4.forter.com
ldproducts.com
cdn4.forter.com
songtextemania.com
srv.clickfuse.com
plfoto.com
api.behavioralengine.com
volzsky.ru
p1.ntvk1.ru
womanandhome.com
tags.tiqcdn.com
schottnyc.com
cdn4.forter.com
elderly.com
cdn4.forter.com
fairwinds.org
cdn.augur.io
lyricsbox.com
srv.clickfuse.com
prnewsonline.com
c.lytics.io
firecracker.me
cdn.augur.io
momentlens.co
cdn.augur.io
7info.ru
p1.ntvk1.ru
analizy.pl
api.behavioralengine.com
muvila.com
st-a.props.id
glavny.tv
p1.ntvk1.ru
multichannelmerchant.com
c.lytics.io
nversia.ru
p1.ntvk1.ru
adindex.ru
p1.ntvk1.ru
fimela.com
st-a.props.id
zipwhip.com
cdn.augur.io
greenmountain.com
cdn.augur.io
golf-monthly.co.uk
tags.tiqcdn.com
ghostbed.com
cdn.augur.io
proxyserver.com
cdn.augur.io
planday.com
cdn.augur.io
zeek.me
cdn4.forter.com
racycles.com
cdn4.forter.com
honeyflow.com
cdn.augur.io
lecturio.com
cdn.augur.io
baseballexpress.com
cdn4.forter.com
zogsports.com
cdn.augur.io
hifx.co.uk
cdn.augur.io
profesor.pl
api.behavioralengine.com
charaktery.eu
api.behavioralengine.com
cultbox.co.uk
srv.clickfuse.com
tabloid-nakita.com
st-a.props.id
storibriti.com
st-a.props.id
trisports.com
cdn.augur.io
aceable.com
cdn.augur.io
rapdose.com
srv.clickfuse.com
xidax.com
cdn.augur.io
uncut.co.uk
tags.tiqcdn.com
abcgiftcards.com
cdn4.forter.com
nutriliving.com
cdn.augur.io
boxycharm.com
cdn.augur.io
sajiansedap.com
st-a.props.id
designpickle.com
cdn.augur.io
yachtingworld.com
tags.tiqcdn.com
petcentric.com
c.lytics.io
studiodaily.com
c.lytics.io
spirithoods.com
cdn.augur.io
techno.id
st-a.props.id
bose.ca
cdn4.forter.com
lyreka.com
srv.clickfuse.com
weboost.com
cdn.augur.io
chiefmarketer.com
c.lytics.io
cliqstudios.com
cdn.augur.io
mojapogoda.com
api.behavioralengine.com
eventmarketer.com
c.lytics.io
gong.io
cdn.augur.io
12zawodnik.pl
api.behavioralengine.com
monq.com
cdn.augur.io
bigstockphoto.mx
cdn.augur.io
choosemuse.com
cdn.augur.io
whatsontv.co.uk
tags.tiqcdn.com
famous.id
st-a.props.id
influenceandco.com
c.lytics.io
libertytax.com
cdn.augur.io
tmpo.co
st-a.props.id
eno.org
c.lytics.io
smolnarod.ru
p1.ntvk1.ru
inwestycje.pl
api.behavioralengine.com
actonservice.com
c.lytics.io
planday.dk
cdn.augur.io
teeki.com
cdn.augur.io
clinicaladvisor.com
c.lytics.io
bbemaildelivery.com
cdn.augur.io
powermag.com
c.lytics.io
bigstockphoto.in
cdn.augur.io
healthleadersmedia.com
c.lytics.io
foliomag.com
c.lytics.io
fn-volga.ru
p1.ntvk1.ru
litter-robot.com
cdn.augur.io
dogomania.com
api.behavioralengine.com
escortradar.com
cdn.augur.io
inkcartridges.com
cdn4.forter.com
vminnovations.com
cdn4.forter.com
aftershokz.com
cdn.augur.io
lifedeathprizes.com
tags.tiqcdn.com
luuna.mx
cdn.augur.io
dayabyzendaya.com
cdn.augur.io
123inkjets.com
cdn4.forter.com
sky-tours.com
cdn4.forter.com
wealthyretirement.com
c.lytics.io
greenmountainenergy.com
cdn.augur.io
fivver.com
cdn4.forter.com
kompas.co.id
st-a.props.id
satellitetoday.com
c.lytics.io
e-podatnik.pl
api.behavioralengine.com
penza-press.ru
p1.ntvk1.ru
worldsoccer.com
tags.tiqcdn.com
ideaonline.co.id
st-a.props.id
purinaone.com
c.lytics.io
healthcarefinancenews.com
c.lytics.io
fitradio.com
cdn.augur.io
brooklynbedding.com
cdn.augur.io
skypicker.com
cdn4.forter.com
roomertravel.com
cdn4.forter.com
youngmoney.com
srv.clickfuse.com
azvideos.com
srv.clickfuse.com
disco-polo.info
api.behavioralengine.com
codefellows.org
cdn.augur.io
bigstock.com.br
cdn.augur.io
proptiger-ws.com
st-a.props.id
segoma.com
cdn4.forter.com
petcube.com
cdn.augur.io
perkbox.com
cdn.augur.io
whatsinthebible.com
cdn.augur.io
act-on.net
c.lytics.io
opploans.com
cdn.augur.io
fiverr.co.uk
cdn4.forter.com
astromagia.pl
api.behavioralengine.com
shootinguk.co.uk
tags.tiqcdn.com
standdesk.co
cdn.augur.io
pinkbasis.com
cdn4.forter.com
shoeline.com
cdn4.forter.com
zferral.com
cdn.augur.io
leadscon.com
c.lytics.io
hcpro.com
c.lytics.io
wkuwanko.pl
api.behavioralengine.com
getmoneymusic.com
srv.clickfuse.com
myhomepay.com
cdn.augur.io
biznes2biznes.com
api.behavioralengine.com
gruntstyle.myshopify.com
cdn.augur.io
womanmagazine.co.uk
tags.tiqcdn.com
lyricsreg.com
srv.clickfuse.com
curaytor.com
cdn.augur.io
hemat.com
st-a.props.id
live-smart.co
tags.tiqcdn.com
minonline.com
c.lytics.io
clearcode.cc
c.lytics.io
kreskowka.pl
api.behavioralengine.com
defensedaily.com
c.lytics.io
om-saratov.ru
p1.ntvk1.ru
experiencegla.com
cdn.augur.io
ministryideaz.com
cdn.augur.io
crystalreports.com
cdn.augur.io
teamexpress.com
cdn4.forter.com
evolvevacationrental.com
cdn.augur.io
countrylife.co.uk
tags.tiqcdn.com
proplan.com
c.lytics.io
missaouniversitario.com.br
cdn.augur.io
synap.ac
cdn.augur.io
niebonatalerzu.blogspot.com
api.behavioralengine.com
clickenergy.com.au
cdn.augur.io
fiver.com
cdn4.forter.com
cynopsis.com
c.lytics.io
zinus.com
cdn.augur.io
infostrefa.com
api.behavioralengine.com
howtomakemoneywithbitcoin.net
cdn.augur.io
huddlebuy.co.uk
cdn.augur.io
bhphoto.com
cdn4.forter.com
malinandgoetz.com
cdn4.forter.com
himssconference.org
c.lytics.io
exoprotein.com
cdn.augur.io
szafunia.pl
api.behavioralengine.com
gettespo.com
cdn.augur.io
regpacks.com
cdn.augur.io
flytographer.com
cdn.augur.io
pap.com.pl
api.behavioralengine.com
aviationtoday.com
c.lytics.io
currentbody.com
cdn4.forter.com
i-talk24.net
cdn.augur.io
40music.com
srv.clickfuse.com
medstudy.com
cdn.augur.io
agorafinancial.co.uk
c.lytics.io
tbseen.com
cdn.augur.io
evematelas.fr
cdn.augur.io
quotefx.com
cdn.augur.io
prawnik.pl
api.behavioralengine.com
branz-bsd.com
st-a.props.id
pbo.co.uk
tags.tiqcdn.com
mysunrun.com
cdn.augur.io
misto.news
p1.ntvk1.ru
damsko.pl
api.behavioralengine.com
stockpile.com
cdn.augur.io
bigstockphoto.es
cdn.augur.io
womansweekly.com
tags.tiqcdn.com
bigroad.com
cdn.augur.io
sztuka-architektury.pl
api.behavioralengine.com
cpenow.com
cdn.augur.io
archinea.pl
api.behavioralengine.com
sobytiya.dp.ua
p1.ntvk1.ru
friskies.com
c.lytics.io
missu.com.br
cdn.augur.io
wildlandtrekking.com
cdn.augur.io
jip.co.id
st-a.props.id
pistollake.com
cdn.augur.io
chemengonline.com
c.lytics.io
portalaktywni.com
api.behavioralengine.com
hifx.com.au
cdn.augur.io
diamondbackcovers.com
cdn.augur.io
mby.com
tags.tiqcdn.com
onephoto.net
api.behavioralengine.com
rugbyworld.com
tags.tiqcdn.com
screambox.com
cdn.augur.io
magazinesdirect.com
tags.tiqcdn.com
superpracodawca.pl
api.behavioralengine.com
banjarmasinpost.co.id
st-a.props.id
havenlife.com
cdn.augur.io
yachtingmonthly.com
tags.tiqcdn.com
todaysmedicaldevelopments.com
c.lytics.io
leesa.co.uk
cdn.augur.io
ibinews.com
tags.tiqcdn.com
wrozka.com.pl
api.behavioralengine.com
yogabed.com
cdn.augur.io
jomadeals.com
cdn4.forter.com
fiveer.com
cdn4.forter.com
fileright.com
cdn.augur.io
womansown.co.uk
tags.tiqcdn.com
e-logistyka.pl
api.behavioralengine.com
cannabisbusinesstimes.com
c.lytics.io
farmersbusinessnetwork.com
cdn.augur.io
smashfund.com
cdn.augur.io
femalemag.com.my
cdn.augur.io
plej.tv
api.behavioralengine.com
suppliesguys.com
cdn4.forter.com
krasnodarmedia.su
p1.ntvk1.ru
strategictechinvestor.com
c.lytics.io
beyondpetfood.com
c.lytics.io
weranda.pl
api.behavioralengine.com
unitedmedicareadvisors.com
cdn.augur.io
rolpetrol.com.pl
api.behavioralengine.com
bearmattress.com
cdn.augur.io
thefield.co.uk
tags.tiqcdn.com
talerzpokus.tv
api.behavioralengine.com
superyachtworld.com
tags.tiqcdn.com
porcys.com
api.behavioralengine.com
opploans-app.com
cdn.augur.io
thevideomode.com
tags.tiqcdn.com
riedelusa.net
cdn4.forter.com
honeyflow.com.au
cdn.augur.io
firepoint.net
cdn.augur.io
aerospacemanufacturinganddesign.com
c.lytics.io
dayabyzendaya.myshopify.com
cdn.augur.io
lyricsdepot.com
srv.clickfuse.com
fivrr.com
cdn4.forter.com
zumbido.es
api.behavioralengine.com
teamexos.com
cdn.augur.io
skyfitapp.com
cdn.augur.io
kidbox.com
cdn4.forter.com
danmccomb.com
cdn4.forter.com
coacdn.com
cdn4.forter.com
electricitywizard.com.au
cdn.augur.io
thisispowder.co.uk
tags.tiqcdn.com
myster.myshopify.com
cdn.augur.io
caratulandia.net
srv.clickfuse.com
decisionhealth.com
c.lytics.io
turing.io
cdn.augur.io
softball.com
cdn4.forter.com
artinfo.pl
api.behavioralengine.com
artifex.ru
p1.ntvk1.ru
anglisci.pl
api.behavioralengine.com
alpinetexashomes.com
cdn.augur.io
brainstormidsupply.com
cdn4.forter.com
macs4u.com
cdn4.forter.com
hifx.co.nz
cdn.augur.io
wartajakarta.com
st-a.props.id
w210.pl
api.behavioralengine.com
anglersmail.co.uk
tags.tiqcdn.com
tuningforum.pl
api.behavioralengine.com
folioshow.com
c.lytics.io
girlabouttech.com
tags.tiqcdn.com
napavalleyfilmfest.org
cdn.augur.io
getmyster.com
cdn.augur.io
canopytax.com
cdn.augur.io
opusonewinery.com
cdn4.forter.com
hcmarketplace.com
c.lytics.io
bluedogrv.com
cdn.augur.io
podvoh.ru
p1.ntvk1.ru
dunejewelry.com
cdn.augur.io
lethalperformance.com
cdn4.forter.com
socialshakeupshow.com
c.lytics.io
proplanveterinarydiets.com
c.lytics.io
shopwings.com.au
cdn.augur.io
codogara.pl
api.behavioralengine.com
athletesperformance.com
cdn.augur.io
wrealu24.eu
api.behavioralengine.com
